---
title: "How to use tissot"
author: "Jannis Fröhlking"
date: "01.07.2021"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tissot)
library(rnaturalearth)
library(sf)
library(rgeos)
```

## Plot on unprojected data
```{r unprojected}
w <- ne_countries(scale = "medium", returnclass = "sf")
w_geom = st_geometry(w)
unprojected = tissot(5)
# plot(w_geom,axes = TRUE, graticule = TRUE)
plot(unprojected, col = "red")
```


## Project on web mercator
```{r web mercator}
x = unprojected
st_crs(x) <- st_crs(3857)
plot(w_geom,axes = TRUE, graticule = TRUE)
plot(x,col = "red")
```

## Project on Eckert-IV
```{r eckert-iv}
# eckert-IV
eckert <- st_transform(x,"+proj=eck4 +ellps=WGS84 +datum=WGS84 +units=m")
w_eck <- st_transform(w_geom,st_crs("+proj=eck4 +ellps=WGS84 +datum=WGS84 +units=m"))
plot(w_eck,axes = TRUE, graticule = TRUE)
plot(eckert,col = "red")
```


## Project on "Equal Earth"
```{r equal-earth}
equal_earth = st_transform(x,8857)
w_ea <- st_transform(w_geom,8857)
plot(w_ea,axes = TRUE, graticule = TRUE)
plot(equal_earth,col = "red")
```

